language: node_js
sudo: required
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
node_js:
- '10'
install:
  - npm ci
script:
  - npm test
  - npm run lint
after_success:
  - npm run release
